# Generated by Django 6.0.5 on 2026-05-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.CharField(max_length=1000)),
                ('ano_lascamento', models.IntegerField()),
                ('genero', models.CharField(max_length=1000)),
            ],
        ),
    ]
